### ISSUE TITLE
Getting the Token but not the last copy of it

### ISSUE THREAD

**Issue by codigoconjuan** [the-road-to-graphql/the-road-to-graphql#12]
Following the tutorial from the book and I'm facing an issue:

I'm able to generate the Token and everything but, when i run this code, looks like the token isn't passed to the apolloServer at the same time:

```
const getMe = async req => {
const token = req.headers['x-token'];
if (token) {
try {
return await jwt.verify(token, process.env.SECRET);
} catch (e) {
throw new AuthenticationError(
'Your session expired. Sign in again.',
);
}
}
};

```

tried to debug this thing, and I sent the token to the console and when the localStorage is empty and try to authenticate a user the TOKEN is generated in the localstorage fine, but in the ApolloServer i have null

then i try again to authenticate and i found that the Token is passed to the ApolloServer but is passing the old token, so i'm getting the message 'Your session expired. Sign in again.', all the time

**Comment by rwieruch** [comment]
Hi @juanpablogdl Can you put your code on GitHub? Which chapter did this happen and did you build your own client for it?

**Comment by codigoconjuan** [comment]
Hello rwieruch

just fixed the problem, i was building a project, then i found your book on Twitter  and i was integrating everything from the book into my project

i found that the secret key wasn't provided into the login resolver :P
