### ISSUE TITLE
Typo on page 11

### ISSUE THREAD

**Issue by ugultopu** [the-road-to-graphql/the-road-to-graphql#33]
Instead of:

Finding the right solution for a given problem is not always simple, and web applications **build** with GraphQL are a good example of how changing times make for constantly evolving challenges.

The right one:

Finding the right solution for a given problem is not always simple, and web applications **built** with GraphQL are a good example of how changing times make for constantly evolving challenges

Sorry 😊

**Comment by rwieruch** [comment]
That's alright. Thank you! You could fix the typo here right away if you want to :)

**Comment by ugultopu** [comment]
Awesome! Didn't realize that the book was in this repo as well. Created the PR.
